name: Deploy to central

on: workflow_dispatch

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
#    strategy:
#      matrix:
#        include:
#          - module: validation
#          - module: schema-json-kotlinx
#          - module: schema-kotlinx-datetime
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    environment: maven-central
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Publish to MavenCentral
      run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
