name: Deploy to central

on: workflow_dispatch

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - module: validation
          - module: schema-json-kotlinx
          - module: schema-kotlinx-datetime
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - uses: actions/cache@v3
      with:
        path: |
          ~/.konan
        key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Publish to MavenCentral
      run: ./gradlew ${{ matrix.module }}:publishToMavenCentral --no-configuration-cache
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}

#    - name: Gradle Publish
#      env:
#        MAVEN_GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
#        MAVEN_GITHUB_PASSWORD: ${{ secrets.MAVEN_GITHUB_PASSWORD }}
#      run: ./gradlew ${{ matrix.module }}:publish
#
#    - name: Gradle jreleaserFullRelease
#      env:
#        JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#        JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
#        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
#        JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.MAVENCENTRAL_SONATYPE_USERNAME }}
#        JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD: ${{ secrets.MAVENCENTRAL_SONATYPE_PASSWORD }}
#        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: ./gradlew ${{ matrix.module }}:jreleaserFullRelease
